### PR TITLE
Add support for Redis 5.0 features, including Streams API

### PR DESCRIPTION
**Pull request by bobby**
I generated a new `commands.edn` in order to address #208.

New `commands.edn` adds commands:

- XLEN
- XADD
- XREADGROUP
- BZPOPMAX
- ZPOPMIN
- XREAD
- XRANGE
- XPENDING
- ZPOPMAX
- XREVRANGE
- BZPOPMIN

and changes command:

- SET

### CODE REVIEW

**Comment by hden** [comment]
Any update on this?

**Comment by tirkarthi** [comment]
Thanks much for the PR @bobby . I wrote a [blog post](https://tirkarthi.github.io/programming/2018/08/17/redis-streams-clojure.html) with this PR and things work well. One command I was missing was the XACK command due to which I was not able to acknowledge the messages read by different consumers in a group. I think it will be an useful addition along with XGROUP command for which you have raised an issue upstream command generation from reference.

Thanks

**Comment by tirkarthi** [comment]
Thanks much @bobby I have verified the usage of new commands in https://github.com/ptaoussanis/carmine/pull/210/commits/ca59a6bf172ebd2a868b1e1a5a8e7fe21f15d693 and they work fine :)

**Comment by bobby** [comment]
Okay, I've updated as of adding XINFO to the mix.  I've tested locally on a rather complex distributed system, and it works well.  @ptaoussanis when are you comfortable merging these changes, after antirez/redis-doc#963 is merged, or could we do before?

**Comment by ptaoussanis** [comment]
Hi Bobby, sorry for the long delay replying. This looks great, will try merge + cut a new release tomorrow 👍Cheers!

**Pull request closed without merging**
