### PR TITLE
added :uri (not :url) example

### PR DESCRIPTION
**Pull request by 0atman**
So that #194 never happens to anyone again (hopefully!)

### CODE REVIEW

**Comment by 0atman** [comment]
It's copy and pasted from [carmine.clj#L28](https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine.clj#L28)

**Comment by 0atman** [comment]
low hanging fruit here, just need a merge

**Comment by 0atman** [comment]
click merge, go on

**Comment by ptaoussanis** [comment]
Tough to resist that, thanks Tristram - sorry for the delay :-)

**Comment by 0atman** [comment]
fantastic. Thank for your help back in May uncovering this!

**Comment by ptaoussanis** [comment]
Np. Thanks for your help back in May with this PR ;-)

**Pull request merged**
