### PR TITLE
Redis Sentinel support

### PR DESCRIPTION
**Pull request by ptaoussanis**
STATUS: Design is basically done, currently awaiting release of new Redis commands.json (https://github.com/antirez/redis-doc/blob/master/commands.json).

### CODE REVIEW

**Comment by neverfox** [comment]
@ptaoussanis What's still blocking this? It's a bummer that the main Redis client for Clojure only works with standalone instances. Let me know how I might help out.

**Comment by ptaoussanis** [comment]
@neverfox What's still blocking this?

Hey Roman, nothing in particular - just lack of interest. When I first looked at implementing this, the implementation spec kept changing. Actually only became stable semi recently, afaik.

At the moment don't have any need of Sentinel or Cluster myself though, and have my hands very full with other priorities - so support will need to come from a PR if anyone else is interested.

Hope that helps, cheers! :-)

**Comment by sunng87** [comment]
+1 for this. We are moving one of our redis to Sentinel managed group. I wish Carmine could support it.

**Comment by ptaoussanis** [comment]
PRs welcome, otherwise happy to implement if someone wants to fund my time on this. Otherwise don't need Sentinel myself so unfortunately no other plans atm, sorry.

**Comment by killme2008** [comment]
I wrote a library to make carmine support sentinel:

  https://github.com/killme2008/carmine-sentinel

Someone may want to try it if  you are interested. Feedback is welcome.

**Comment by ptaoussanis** [comment]
@killme2008  Thanks Dennis, will try take a look at the weekend. Cheers! :-)

**Comment by ptaoussanis** [comment]
Closing, a new implementation is on the v4 branch 👍

**Pull request closed without merging**
