### PR TITLE
Migrate tests

### PR DESCRIPTION
**Pull request by firesofmay**
Migration from expectations to clojure.test is done.
Please run all the tests yourself once as well as I haven't run tundra tests (I haven't tried to migrate tundra S3 tests to local disk yet).

Here's the test output that I ran:
```
$ lein with-profile "+1.9:+1.8:+1.7:+1.6:+1.5" test taoensso.carmine.tests.main taoensso.carmine.tests.locks taoensso.carmine.tests.message-queue

Performing task 'test' with profile(s): 'base,system,user,provided,dev,1.9'

lein test taoensso.carmine.tests.main

Benching (this can take some time)
----------------------------------

Lap 1/1...
{:wcar 95, :ping 517, :set 433, :get 656, :roundtrip 613, :ping-pipelined 2143}

Done! (Time for cake?)

lein test taoensso.carmine.tests.locks

lein test taoensso.carmine.tests.message-queue

Ran 51 tests containing 191 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'base,system,user,provided,dev,1.8'

lein test taoensso.carmine.tests.main

Benching (this can take some time)
----------------------------------

Lap 1/1...
{:wcar 97, :ping 615, :set 480, :get 597, :roundtrip 575, :ping-pipelined 2203}

Done! (Time for cake?)

lein test taoensso.carmine.tests.locks

lein test taoensso.carmine.tests.message-queue

Ran 51 tests containing 191 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'base,system,user,provided,dev,1.7'

lein test taoensso.carmine.tests.main

Benching (this can take some time)
----------------------------------

Lap 1/1...
{:wcar 126, :ping 592, :set 457, :get 478, :roundtrip 567, :ping-pipelined 2200}

Done! (Time for cake?)

lein test taoensso.carmine.tests.locks

lein test taoensso.carmine.tests.message-queue

Ran 51 tests containing 191 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'base,system,user,provided,dev,1.6'

lein test taoensso.carmine.tests.main

Benching (this can take some time)
----------------------------------

Lap 1/1...
{:wcar 92, :ping 618, :set 491, :get 548, :roundtrip 572, :ping-pipelined 2147}

Done! (Time for cake?)

lein test taoensso.carmine.tests.locks

lein test taoensso.carmine.tests.message-queue

Ran 51 tests containing 191 assertions.
0 failures, 0 errors.
Performing task 'test' with profile(s): 'base,system,user,provided,dev,1.5'

lein test taoensso.carmine.tests.main

Benching (this can take some time)
----------------------------------

Lap 1/1...
{:wcar 45, :ping 478, :set 429, :get 462, :roundtrip 542, :ping-pipelined 2199}

Done! (Time for cake?)

lein test taoensso.carmine.tests.locks

lein test taoensso.carmine.tests.message-queue

Ran 51 tests containing 191 assertions.
0 failures, 0 errors.
```

Let me know if there's something I missed.
Thanks :)

### CODE REVIEW

**Comment by firesofmay** [comment]
This fixes #191

**Comment by ptaoussanis** [comment]
You're a champion, thank you! Will try get this merged tomorrow.

**Comment by firesofmay** [comment]
@ptaoussanis Thank you! :)

**Comment by firesofmay** [comment]
@ptaoussanis Any updates on this?

**Comment by ptaoussanis** [comment]
Hi Mayank, sorry for the delay - have had my hands quite full. Will try get this in later in the week!

**Comment by firesofmay** [comment]
@ptaoussanis Sure :)

**Comment by ptaoussanis** [comment]
Merging now!

**Pull request closed without merging**
