### PR TITLE
[ring middleware] Reset session expiration on every read

### PR DESCRIPTION
**Pull request by svdo**
This change introduces a new option `:extend-on-read?` to the Ring middleware. By default it is `false`. When `false`, the session expiration will be set when it is created ~~(and not changed afterwards)~~ and when it is written (which normally doesn't happen when using the ring-session middleware). When `true` the session expiration is reset on every read, so that the session is always valid for the set number of seconds _after it was last used_.

Updated pull request for #259.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
@svdo Thanks Stefan! Will look at merging next time I'm doing some batched work on Carmine.

Just a heads-up that this part of your understanding isn't accurate:
> When false, the session expiration will be set when it is created (and not changed afterwards)

When false, the session is also renewed on any session writes (changes).

I.e. the options will be:

- false (default): renew session only on session writes
- true: renew session also on session reads

Hope that makes sense!

**Comment by svdo** [comment]
Yes I understand, thanks for clarifying!!

**Comment by ptaoussanis** [comment]
@svdo Will be merged in next release, thanks Stefan! Apologies for the long delay.

**Comment by svdo** [comment]
No problem at all @ptaoussanis, I've been using my fork so that didn't cause any issues for me :)

**Pull request closed without merging**
