### PR TITLE
Expand shortened links for more future-proof comments

### PR DESCRIPTION
**Pull request by timmc**
Links rot at a tremendous rate (maybe 10% per year? higher?) so these
comments should have at least archive.org-compatible links.

In the case of the Google Groups link I included the post title because
the URL appeared particularly unstable.

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Tim,

> Links rot at a tremendous rate (maybe 10% per year? higher?)

Do you have a reference for this? My understanding was that these links are intended to be ~permanent?

**Comment by timmc** [comment]
Source is the owner of Pinboard, a bookmarking site. [Actual number was 5%](http://idlewords.com/talks/web_design_first_100_years.htm):

> Since I run a bookmarking site for a living, I've done a little research on link rot myself. Bookmarks are different from regular URLs, because presumably anything you've bookmarked was once worth keeping. What I've learned is, about 5% of this disappears every year, at a pretty steady rate. A customer of mine just posted how 90% of what he saved in 1997 is gone. This is unfortunately typical. 

Google runs goo.gl as a free service. There's no guarantee it will continue to operate; any day it might go the way of Google Reader, Google Code, etc. The service could also be down at any point. The real URLs decay at a certain rate as well. (Blogs and javadoc sites in particular are pretty flaky.) If *both* are down, it's impossible to discover what the comment was trying to point to.

**Comment by ptaoussanis** [comment]
Hi Tim, thanks for the source. Just to clarify since it's a long page and I wasn't sure where to look: the owner of Pinboard suggests that Google recycles 5% of their goo.gl URLs each year?

**Comment by timmc** [comment]
Ah, no, he's talking about links in general. I suppose that as long as goo.gl stays up, if one of the target pages goes down, one could still use curl to determine the target URL and use archive.org from there as usual... I was more coming from the "links are generally not stable, more of them is worse" stance on link shorteners. (I think they're fine for billboards and such, but they're... let's say, not archival-quality. :-P)

**Comment by ptaoussanis** [comment]
Hi there! Sorry, closing this as part of issue triage. Might make sense to try do this in future, just not a priority atm + trying to focus time where it'll be most helpful.

Appreciate your time + input on this. Cheers! :-)

**Comment by timmc** [comment]
Google will be shutting down their goo.gl service. For now, they say existing links will continue to work, but they could discontinue it at any time.

https://www.seroundtable.com/google-goo-gl-url-shortener-closing-25532.html

If you're interested now, I could re-work this patch to make it applyable again.

**Pull request closed without merging**
