### PR TITLE
Add ssl option for connection spec

### PR DESCRIPTION
**Pull request by hackbert**
Hey Peter,
I really like carmine and have used it successfully for quite a while now.
Now I have to move a considerable code base to AWS and therefore also use ElastiCache. Since all traffic inside the AWS has to somehow be encrypted, I need a ssl parameter for our carmine connections. I know that this has been [discussed already](https://github.com/ptaoussanis/carmine/issues/151), but the cloud aspect was not mentioned there and so we thought I would give it another try.

Please see the pull request as a very rudimentary proposed implementation that I would further refine if you're open to the idea.

### CODE REVIEW

**Comment by alphaone** [comment]
That would be so goooood!

**Comment by ptaoussanis** [comment]
Hi Carl, on board to see a refined PR for this - thank you :+1:

**Comment by hackbert** [comment]
It is a bit more polished now. Do you have any feedback/suggestions?

**Comment by ptaoussanis** [comment]
Merging manually in a moment, thanks again for this :+1:

**Pull request closed without merging**
